items_show:
    path:      /
    controller: App\Controller\ItemController::showItems

items_add:
    path:      /items/add
    controller: App\Controller\ItemController::addItem

items_download:
    path:      /items/download/{downloadOption}
    controller: App\Controller\ItemController::downloadItem
