items_show:
    path:      /
    controller: App\Controller\ItemController::showItems

items_add:
    path:      /items/add
    controller: App\Controller\ItemController::addItem

items_remove:
    path:      /items/remove/{itemId}
    controller: App\Controller\ItemController::removeItem

items_download:
    path:      /items/download/{downloadOption}
    controller: App\Controller\ItemController::downloadItem
