show_items:
    path:      /
    controller: App\Controller\ItemController::showItems

download_item:
    path:      /download_items/{downloadOption}
    controller: App\Controller\ItemController::downloadItem
