parameters:
    locale: 'pl'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    api.item.guzzle:
         class: GuzzleHttp\Client
         arguments:
            - base_uri: '%env(API_ITEM_URL)%'

    ApiClient\Service\Item:
         arguments: ['@api.item.guzzle']

    ApiClient\Service\ItemInterface: '@ApiClient\Service\Item'
